"""API-key based multi-agent runtime: providers, local tools, permissions, agent loop.

See `docs/orchestra-api-runtime.md` for the full design writeup.
"""

from __future__ import annotations

from orchestra_api.cancellation import CancellationToken, OperationCancelled
from orchestra_api.events import (
    CollectingSink,
    CompactionApplied,
    Event,
    EventSink,
    RunFailed,
    RunFinished,
    RunStarted,
    SubagentSpawned,
    ToolCallFinished,
    ToolCallStarted,
    TurnFinished,
    TurnStarted,
)
from orchestra_api.identity import (
    SCHEMA_VERSION,
    AgentRef,
    RunRef,
    TurnRef,
    new_agent_ref,
    new_id,
    new_run_ref,
    new_turn_ref,
)
from orchestra_api.models import (
    ContentBlock,
    Message,
    ModelRequest,
    ModelResponse,
    Role,
    ToolCall,
    ToolResult,
    TextBlock,
    Usage,
    wire_tool_call_ids,
)
from orchestra_api.tools.metadata import (
    FAIL_CLOSED,
    InterruptBehavior,
    ResultHint,
    ToolEffect,
    ToolMetadata,
    safe_metadata,
)
from orchestra_api.tools.web_fetch import WebFetchTool
from orchestra_api.web import (
    DEFAULT_FETCH_TIMEOUT_SECONDS,
    MAX_FETCH_BYTES,
    MAX_REDIRECTS,
    FetchedPage,
    WebFetchError,
    fetch_url,
)
from orchestra_api.web_domains import preapproved_domains
from orchestra_api.web_search import (
    DEFAULT_SEARCH_LIMIT,
    DEFAULT_SEARCH_TIMEOUT_SECONDS,
    MAX_SEARCH_LIMIT,
    MIN_SEARCH_LIMIT,
    HttpJsonSearchBackend,
    SearchBackend,
    SearchBackendError,
    SearchEndpoint,
    SearchHit,
    search_endpoint,
    search_endpoints,
)
from orchestra_api.tools.web_search import WebSearchTool
from orchestra_api.serialization import (
    content_blocks_from_json,
    content_blocks_to_json,
    message_from_json,
    message_to_json,
    tool_call_from_json,
    tool_call_to_json,
    tool_result_from_json,
    tool_result_to_json,
)
from orchestra_api.session import (
    LoadedRun,
    SessionError,
    SessionStore,
    TranscriptError,
    TranscriptWriter,
    default_sessions_root,
    fork_run,
    load_run,
    read_records,
    resume_run,
)
from orchestra_api.runner import resume_task

__all__ = [
    "AgentRef",
    "CancellationToken",
    "CollectingSink",
    "CompactionApplied",
    "ContentBlock",
    "Event",
    "EventSink",
    "FetchedPage",
    "FAIL_CLOSED",
    "InterruptBehavior",
    "MAX_FETCH_BYTES",
    "MAX_REDIRECTS",
    "MAX_SEARCH_LIMIT",
    "LoadedRun",
    "Message",
    "ModelRequest",
    "ModelResponse",
    "OperationCancelled",
    "ResultHint",
    "Role",
    "RunFailed",
    "RunFinished",
    "RunRef",
    "RunStarted",
    "SCHEMA_VERSION",
    "SearchBackend",
    "SearchBackendError",
    "SearchEndpoint",
    "SearchHit",
    "SessionError",
    "SessionStore",
    "SubagentSpawned",
    "TextBlock",
    "ToolCall",
    "ToolCallFinished",
    "ToolCallStarted",
    "ToolEffect",
    "ToolMetadata",
    "ToolResult",
    "TranscriptError",
    "TranscriptWriter",
    "TurnFinished",
    "TurnRef",
    "TurnStarted",
    "Usage",
    "WebFetchError",
    "WebFetchTool",
    "WebSearchTool",
    "DEFAULT_FETCH_TIMEOUT_SECONDS",
    "DEFAULT_SEARCH_LIMIT",
    "DEFAULT_SEARCH_TIMEOUT_SECONDS",
    "HttpJsonSearchBackend",
    "MIN_SEARCH_LIMIT",
    "fetch_url",
    "content_blocks_from_json",
    "content_blocks_to_json",
    "default_sessions_root",
    "fork_run",
    "load_run",
    "message_from_json",
    "message_to_json",
    "new_agent_ref",
    "new_id",
    "new_run_ref",
    "new_turn_ref",
    "preapproved_domains",
    "search_endpoint",
    "search_endpoints",
    "safe_metadata",
    "read_records",
    "resume_run",
    "resume_task",
    "wire_tool_call_ids",
    "tool_call_from_json",
    "tool_call_to_json",
    "tool_result_from_json",
    "tool_result_to_json",
]
